/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// 自动生成文件：可阅读但不建议手工维护，重新生成时会被覆盖。
// biome-ignore lint: disable
export { }
declare global {
  const ElMessage: typeof import('element-plus/es').ElMessage
}
